#!/bin/bash

export ARM=$PWD/../../../toolchain/arm-2009q3/bin
export PATH=$ARM:$PATH
export VERSION=1.4
export SIZES="`echo {80..140..10} {160..400..20}`"
export CACHE="5 44"
export OUTPUT=$PWD/../cLK-out
export O_ALL=$OUTPUT/allInOne
export O_ZIP=$OUTPUT/zips

make clean
mkdir -p $O_ALL
mkdir -p $O_ZIP
rm -rf $O_ALL/{*.nbh,*.zip}
rm -rf $O_ZIP/*.zip

for cache in $CACHE
do
  for size in $SIZES
  do
    sed -i s/DEFINES\ +=\ SYSTEM_PARTITION_SIZE=.*/DEFINES\ +=\ SYSTEM_PARTITION_SIZE=${size}/ lk/target/htcleo/rules.mk
    sed -i s/DEFINES\ +=\ CACHE_PARTITION_SIZE=.*/DEFINES\ +=\ CACHE_PARTITION_SIZE=${cache}/ lk/target/htcleo/rules.mk
    sed -i s/system\ .*/system\ ${size}M/ build-stuff/readme.txt
    sed -i s/cache\ .*/cache\ ${cache}M/ build-stuff/readme.txt
    make partition
    pushd build-stuff
      rm -rf $O_ZIP/cLK_${VERSION}_${size}_${cache}.zip
      mv ../bin/RUU_signed.nbh .
      zip -9Dr $O_ZIP/cLK_${VERSION}_${size}_${cache}.zip readme.txt CustomRUU.exe RUU_signed.nbh
      cp RUU_signed.nbh $O_ALL/RUU_signed-${size}-${cache}.nbh
      rm -rf RUU_signed.nbh
    popd
  done
done

pushd $O_ALL
rm -rf cLK_${VERSION}_layouts_arif.zip
zip -9Dr cLK_${VERSION}_layouts_arif.zip *.nbh
popd
